name: CI

on:
  push:
    branches:
      - main
      - 'feature/*'  # Run on feature branches
  pull_request:
    branches:
      - main
      - 'feature/*'  # Run on pull requests to main and feature branches

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Change to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint  # Make sure you have a lint script defined in your package.json

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Change to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build  # Make sure you have a build script defined in your package.json
